/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'contentHindi' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'titleHindi' : IDL.Text,
  'date' : Time,
  'isActive' : IDL.Bool,
});
export const Cow = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'healthStatus' : IDL.Text,
  'addedDate' : Time,
  'breed' : IDL.Text,
});
export const Donation = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'donorName' : IDL.Text,
  'message' : IDL.Text,
  'amount' : IDL.Float64,
  'purpose' : IDL.Text,
});
export const HealthRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'date' : Time,
  'cowId' : IDL.Nat,
  'vetName' : IDL.Text,
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addCow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addDonation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addHealthRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCow' : IDL.Func([IDL.Nat], [], []),
  'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllCows' : IDL.Func([], [IDL.Vec(Cow)], ['query']),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getCow' : IDL.Func([IDL.Nat], [Cow], ['query']),
  'getDonation' : IDL.Func([IDL.Nat], [Donation], ['query']),
  'getHealthRecord' : IDL.Func([IDL.Nat], [HealthRecord], ['query']),
  'getHealthRecordsByCow' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(HealthRecord)],
      ['query'],
    ),
  'updateCow' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'contentHindi' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'titleHindi' : IDL.Text,
    'date' : Time,
    'isActive' : IDL.Bool,
  });
  const Cow = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'healthStatus' : IDL.Text,
    'addedDate' : Time,
    'breed' : IDL.Text,
  });
  const Donation = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'donorName' : IDL.Text,
    'message' : IDL.Text,
    'amount' : IDL.Float64,
    'purpose' : IDL.Text,
  });
  const HealthRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'date' : Time,
    'cowId' : IDL.Nat,
    'vetName' : IDL.Text,
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addCow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addDonation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addHealthRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCow' : IDL.Func([IDL.Nat], [], []),
    'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllCows' : IDL.Func([], [IDL.Vec(Cow)], ['query']),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getCow' : IDL.Func([IDL.Nat], [Cow], ['query']),
    'getDonation' : IDL.Func([IDL.Nat], [Donation], ['query']),
    'getHealthRecord' : IDL.Func([IDL.Nat], [HealthRecord], ['query']),
    'getHealthRecordsByCow' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(HealthRecord)],
        ['query'],
      ),
    'updateCow' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };