/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'contentHindi' : string,
  'title' : string,
  'content' : string,
  'titleHindi' : string,
  'date' : Time,
  'isActive' : boolean,
}
export interface Cow {
  'id' : bigint,
  'age' : bigint,
  'name' : string,
  'description' : string,
  'healthStatus' : string,
  'addedDate' : Time,
  'breed' : string,
}
export interface Donation {
  'id' : bigint,
  'date' : Time,
  'donorName' : string,
  'message' : string,
  'amount' : number,
  'purpose' : string,
}
export interface HealthRecord {
  'id' : bigint,
  'status' : string,
  'date' : Time,
  'cowId' : bigint,
  'vetName' : string,
  'notes' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAnnouncement' : ActorMethod<
    [string, string, string, string, boolean],
    bigint
  >,
  'addCow' : ActorMethod<[string, string, bigint, string, string], bigint>,
  'addDonation' : ActorMethod<[string, number, string, string], bigint>,
  'addHealthRecord' : ActorMethod<[bigint, string, string, string], bigint>,
  'deleteCow' : ActorMethod<[bigint], undefined>,
  'getActiveAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllCows' : ActorMethod<[], Array<Cow>>,
  'getAllDonations' : ActorMethod<[], Array<Donation>>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getCow' : ActorMethod<[bigint], Cow>,
  'getDonation' : ActorMethod<[bigint], Donation>,
  'getHealthRecord' : ActorMethod<[bigint], HealthRecord>,
  'getHealthRecordsByCow' : ActorMethod<[bigint], Array<HealthRecord>>,
  'updateCow' : ActorMethod<
    [bigint, string, string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];